- name: feature
  description: New feature to be implemented | Nieuwe functionaliteit toevoegen
  color: "1D76DB"

- name: enhancement
  description: Improvement to an existing feature | Verbetering van bestaande functionaliteit
  color: "84b6eb"

- name: bug
  description: Something isn't working | Er werkt iets niet goed (bug)
  color: "D73A4A"

- name: refactor
  description: Code cleanup or structure change | Code herschrijven zonder functionaliteit te wijzigen
  color: "FBCA04"

- name: test
  description: Adding or improving tests | Testen toevoegen of verbeteren
  color: "5319E7"

- name: QA
  description: Quality assurance or production issue | Kwaliteitscontrole of productieprobleem
  color: "BFDADC"

- name: UI
  description: User Interface changes | Aanpassingen aan gebruikersinterface
  color: "0E8A16"

- name: UX
  description: User experience improvements | Verbetering van de gebruikservaring
  color: "006B75"

- name: responsive
  description: Mobile/responsive layout fixes | Aanpassingen voor mobiel of responsive gedrag
  color: "FF8C00"

- name: database
  description: Database schema or query changes | Wijzigingen aan D1-database of SQL-query’s
  color: "5319E7"

- name: auth
  description: Authentication logic or security | Authenticatie en beveiligingslogica
  color: "8A2BE2"

- name: api
  description: Public/private API changes or improvements | Wijzigingen of toevoegingen aan de API
  color: "0052CC"

- name: documentation
  description: Changes to docs or README | Aanpassingen aan documentatie of README
  color: "0075CA"

- name: discussion
  description: Topic or decision that needs team input | Bespreekpunt of beslissing met het team
  color: "CCCCCC"

- name: blocked
  description: Blocked by another issue | Geblokkeerd door andere taak
  color: "E4E669"

- name: wontfix
  description: Issue won't be resolved | Wordt bewust niet opgelost
  color: "000000"

- name: duplicate
  description: Same as another existing issue | Dubbele issue, al gemeld
  color: "cfd3d7"

- name: help wanted
  description: Extra help or input needed | Hulp of input van anderen gewenst
  color: "128A0C"

- name: priority: high
  description: Needs immediate attention | Hoge prioriteit, snel oppakken
  color: "B60205"

- name: priority: medium
  description: Important but not urgent | Normale prioriteit
  color: "D93F0B"

- name: priority: low
  description: Can be picked up later | Lage prioriteit, geen haast
  color: "E4E669"
