name: github-label-sync

on:
  push:
    branches:
      - website
    paths:
      - .github/labels.yml
      - .github/workflows/github-label-sync.yml
  workflow_dispatch:

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: r7kamura/github-label-sync-action@v0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          config_file: .github/labels.yml
