name: Sync GitHub Labels

on:
  push:
    branches:
      - website

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Sync labels
        uses: lannonbr/label-sync-action@v3
        with:
          manifest: .github/labels.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
